name: CI/CD Portfolio Deployment

on:
  push:
    branches: [ main ] # Runs every time you push to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy via SSH Proxy Jump
        uses: appleboy/ssh-action@v1.0.3
        with:
          # Target (The Private Instance)
          host: ${{ secrets.PRIVATE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_KEY }}
          
          # The "Bridge" (The Bastion Host)
          proxy_host: ${{ secrets.BASTION_IP }}
          proxy_username: ${{ secrets.REMOTE_USER }}
          proxy_key: ${{ secrets.SSH_KEY }}
          
          script: |
            cd ~/my-portfolio
            git pull origin main
            npm install
            npm run build
            
            # Use --cwd to force PM2 to the correct folder
            pm2 restart portfolio --update-env --cwd ~/my-portfolio || pm2 start npm --name "portfolio" --cwd ~/my-portfolio -- start
            pm2 save

      - name: Purge Cloudflare Cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}